// Disallow the console window on Windows release builds so the app opens
// as a clean GUI with no terminal flashing behind it. The price is that such
// a process starts with no stdout/stderr, so --debug opens a console of its
// own and --cli attaches to the launching terminal (see win_integration).
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod app;
mod banner;
mod cli;
mod debug_log;
mod disk_space;
mod mft;
mod scanner;
mod theme;
mod treemap;
#[cfg(windows)]
mod win_integration;

use app::WyvernScanApp;

/// The window/taskbar icon, as raw RGBA baked in at compile time. Raw pixels
/// (generated by `assets/make_icon.py`) mean no image-decoding dependency is
/// needed just to show an icon.
fn window_icon() -> eframe::egui::IconData {
    eframe::egui::IconData {
        rgba: include_bytes!("../assets/icon-256.rgba").to_vec(),
        width: 256,
        height: 256,
    }
}

fn main() -> eframe::Result<()> {
    let debug_requested = std::env::args().any(|a| a == "--debug");
    if debug_requested {
        #[cfg(windows)]
        win_integration::open_console();
        // In console mode stdout carries the report, so debug lines go to
        // stderr there (`--cli --json --debug > report.json` stays valid).
        if std::env::args().any(|a| a == "--cli") {
            debug_log::route_to_stderr();
        }
        debug_log::init();
    }

    // Console-only mode for servers with no display: parsed and run before
    // anything below this point touches eframe/winit, so it works even
    // where no graphical context could ever be created.
    //
    // On Windows this must come first: `--help` and argument errors print
    // while parsing, and a release exe has nowhere to print until a console
    // is attached. (`--debug` already opened its own console above.)
    #[cfg(windows)]
    {
        if !debug_requested && std::env::args().any(|a| a == "--cli") {
            win_integration::attach_console();
        }
    }
    if let Some(cli_args) = cli::parse_args() {
        cli::exit(cli::run(cli_args));
    }

    #[cfg(windows)]
    let elevated = win_integration::is_elevated();
    #[cfg(not(windows))]
    let elevated = false;

    let title = if elevated {
        "WyvernScan - fast disk space explorer (Admin)".to_string()
    } else {
        "WyvernScan - fast disk space explorer".to_string()
    };

    let options = eframe::NativeOptions {
        viewport: eframe::egui::ViewportBuilder::default()
            .with_title(&title)
            .with_icon(window_icon())
            .with_inner_size([1120.0, 700.0])
            .with_min_inner_size([640.0, 420.0]),
        ..Default::default()
    };

    let result = eframe::run_native(
        &title,
        options,
        Box::new(move |cc| {
            theme::apply(&cc.egui_ctx);
            Box::new(WyvernScanApp::new(cc, elevated))
        }),
    );

    if let Err(e) = &result {
        eprintln!(
            "Failed to start the graphical interface ({e}).\n\
             If this is a server or other machine with no display, use console mode instead:\n\
             \n    wyvernscan --cli <path>\n    wyvernscan --cli --entire-system\n    wyvernscan --cli --help\n"
        );
    }
    result
}
